name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pyinstaller
    
    - name: List files
      run: |
        dir
        echo "Python files:"
        dir *.py
        echo "Image files:"
        dir *.png
    
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --add-data "*.png;." --name "FruitGame" "砖了个砖.py"
    
    - name: List build output
      run: |
        echo "Contents of dist folder:"
        dir dist
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: dist/FruitGame.exe
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/FruitGame.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}